-- CreateTable
CREATE TABLE "pertumbuhan_laki_laki" (
    "id" SERIAL NOT NULL,
    "day" INTEGER NOT NULL,
    "l_height" DOUBLE PRECISION,
    "m_height" DOUBLE PRECISION,
    "s_height" DOUBLE PRECISION,
    "sd4neg_height" DOUBLE PRECISION,
    "sd3neg_height" DOUBLE PRECISION,
    "sd2neg_height" DOUBLE PRECISION,
    "sd1neg_height" DOUBLE PRECISION,
    "sd0_height" DOUBLE PRECISION,
    "sd1_height" DOUBLE PRECISION,
    "sd2_height" DOUBLE PRECISION,
    "sd3_height" DOUBLE PRECISION,
    "sd4_height" DOUBLE PRECISION,
    "p01_height" DOUBLE PRECISION,
    "p1_height" DOUBLE PRECISION,
    "p3_height" DOUBLE PRECISION,
    "p5_height" DOUBLE PRECISION,
    "p10_height" DOUBLE PRECISION,
    "p15_height" DOUBLE PRECISION,
    "p25_height" DOUBLE PRECISION,
    "p50_height" DOUBLE PRECISION,
    "p75_height" DOUBLE PRECISION,
    "p85_height" DOUBLE PRECISION,
    "p90_height" DOUBLE PRECISION,
    "p95_height" DOUBLE PRECISION,
    "p97_height" DOUBLE PRECISION,
    "p99_height" DOUBLE PRECISION,
    "p999_height" DOUBLE PRECISION,
    "sd4neg_weight" DOUBLE PRECISION,
    "sd3neg_weight" DOUBLE PRECISION,
    "sd2neg_weight" DOUBLE PRECISION,
    "sd1neg_weight" DOUBLE PRECISION,
    "sd0_weight" DOUBLE PRECISION,
    "sd1_weight" DOUBLE PRECISION,
    "sd2_weight" DOUBLE PRECISION,
    "sd3_weight" DOUBLE PRECISION,
    "sd4_weight" DOUBLE PRECISION,
    "p01_weight" DOUBLE PRECISION,
    "p1_weight" DOUBLE PRECISION,
    "p3_weight" DOUBLE PRECISION,
    "p5_weight" DOUBLE PRECISION,
    "p10_weight" DOUBLE PRECISION,
    "p15_weight" DOUBLE PRECISION,
    "p25_weight" DOUBLE PRECISION,
    "p50_weight" DOUBLE PRECISION,
    "p75_weight" DOUBLE PRECISION,
    "p85_weight" DOUBLE PRECISION,
    "p90_weight" DOUBLE PRECISION,
    "p95_weight" DOUBLE PRECISION,
    "p97_weight" DOUBLE PRECISION,
    "p99_weight" DOUBLE PRECISION,
    "p999_weight" DOUBLE PRECISION,
    "l_weight" DOUBLE PRECISION,
    "m_weight" DOUBLE PRECISION,
    "s_weight" DOUBLE PRECISION,

    CONSTRAINT "pertumbuhan_laki_laki_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pertumbuhan_perempuan" (
    "id" SERIAL NOT NULL,
    "day" INTEGER NOT NULL,
    "l_height" DOUBLE PRECISION,
    "m_height" DOUBLE PRECISION,
    "s_height" DOUBLE PRECISION,
    "sd4neg_height" DOUBLE PRECISION,
    "sd3neg_height" DOUBLE PRECISION,
    "sd2neg_height" DOUBLE PRECISION,
    "sd1neg_height" DOUBLE PRECISION,
    "sd0_height" DOUBLE PRECISION,
    "sd1_height" DOUBLE PRECISION,
    "sd2_height" DOUBLE PRECISION,
    "sd3_height" DOUBLE PRECISION,
    "sd4_height" DOUBLE PRECISION,
    "p01_height" DOUBLE PRECISION,
    "p1_height" DOUBLE PRECISION,
    "p3_height" DOUBLE PRECISION,
    "p5_height" DOUBLE PRECISION,
    "p10_height" DOUBLE PRECISION,
    "p15_height" DOUBLE PRECISION,
    "p25_height" DOUBLE PRECISION,
    "p50_height" DOUBLE PRECISION,
    "p75_height" DOUBLE PRECISION,
    "p85_height" DOUBLE PRECISION,
    "p90_height" DOUBLE PRECISION,
    "p95_height" DOUBLE PRECISION,
    "p97_height" DOUBLE PRECISION,
    "p99_height" DOUBLE PRECISION,
    "p999_height" DOUBLE PRECISION,
    "sd4neg_weight" DOUBLE PRECISION,
    "sd3neg_weight" DOUBLE PRECISION,
    "sd2neg_weight" DOUBLE PRECISION,
    "sd1neg_weight" DOUBLE PRECISION,
    "sd0_weight" DOUBLE PRECISION,
    "sd1_weight" DOUBLE PRECISION,
    "sd2_weight" DOUBLE PRECISION,
    "sd3_weight" DOUBLE PRECISION,
    "sd4_weight" DOUBLE PRECISION,
    "p01_weight" DOUBLE PRECISION,
    "p1_weight" DOUBLE PRECISION,
    "p3_weight" DOUBLE PRECISION,
    "p5_weight" DOUBLE PRECISION,
    "p10_weight" DOUBLE PRECISION,
    "p15_weight" DOUBLE PRECISION,
    "p25_weight" DOUBLE PRECISION,
    "p50_weight" DOUBLE PRECISION,
    "p75_weight" DOUBLE PRECISION,
    "p85_weight" DOUBLE PRECISION,
    "p90_weight" DOUBLE PRECISION,
    "p95_weight" DOUBLE PRECISION,
    "p97_weight" DOUBLE PRECISION,
    "p99_weight" DOUBLE PRECISION,
    "p999_weight" DOUBLE PRECISION,
    "l_weight" DOUBLE PRECISION,
    "m_weight" DOUBLE PRECISION,
    "s_weight" DOUBLE PRECISION,

    CONSTRAINT "pertumbuhan_perempuan_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "pertumbuhan_laki_laki_day_key" ON "pertumbuhan_laki_laki"("day");

-- CreateIndex
CREATE UNIQUE INDEX "pertumbuhan_perempuan_day_key" ON "pertumbuhan_perempuan"("day");
